# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170827_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
