# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170827_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='vote',
            new_name='bad',
        ),
        migrations.AddField(
            model_name='news',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
