# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170827_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
