# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporter',
            old_name='start',
            new_name='star',
        ),
    ]
